# ARKALIA ARIA - Docker Compose
version: '3.8'

services:
  aria:
    build: .
    ports:
      - "8001:8001"
    environment:
      - ARIA_ENV=production
      - DATABASE_URL=sqlite:///./aria.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - aria
    restart: unless-stopped

volumes:
  aria_data:
  aria_logs:
