name: arkalia_aria
description: ARKALIA ARIA - Research Intelligence Assistant Mobile App
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.7296
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1

  # HTTP & API
  http: ^1.1.0
  dio: ^5.4.0
  connectivity_plus: ^5.0.2

  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0

  # Utils
  intl: ^0.19.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1

  # Notifications
  flutter_local_notifications: ^16.3.2
  firebase_messaging: ^14.7.10

  # Permissions
  permission_handler: ^11.3.1

  # File System
  path_provider: ^2.1.2
  file_picker: ^6.1.1

  # Health & Sensors
  health: ^10.0.0
  pedometer: ^3.0.1
  device_info_plus: ^9.1.1

  # Charts & Visualization
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^23.2.7

  # UI Components
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  pull_to_refresh: ^2.0.0
  flutter_slidable: ^3.0.1

  # Security
  crypto: ^3.0.3
  encrypt: ^5.0.1

  # Background Tasks
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
